//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputSystem_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem_Actions"",
    ""maps"": [
        {
            ""name"": ""Controls"",
            ""id"": ""8fd020fe-3148-47c2-9c84-2c245fec15bc"",
            ""actions"": [
                {
                    ""name"": ""Joystick_Left"",
                    ""type"": ""Value"",
                    ""id"": ""d8392ef6-ce8e-40a5-8836-8e84e43456a9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Joystick_Right"",
                    ""type"": ""Value"",
                    ""id"": ""e579adb1-1ef1-4619-97c9-a7950eb045ec"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger_Left"",
                    ""type"": ""Value"",
                    ""id"": ""7deb4719-09f8-4c97-aad9-4c873743317a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger_Right"",
                    ""type"": ""Value"",
                    ""id"": ""a921cfcf-2895-4b0d-8520-2ea140e970d2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Dpad_Up"",
                    ""type"": ""Button"",
                    ""id"": ""b9c861c1-d2f0-4a55-b7d0-bfe1006d14be"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Dpad_Down"",
                    ""type"": ""Button"",
                    ""id"": ""cfe7c1b1-5a0e-450c-9342-1e115f774ee3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Dpad_Left"",
                    ""type"": ""Button"",
                    ""id"": ""91a9523f-d9fd-4191-9264-f44659d64847"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Dpad_Right"",
                    ""type"": ""Button"",
                    ""id"": ""8800211e-aa87-471e-83ee-0fd749fcd212"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Face_North"",
                    ""type"": ""Button"",
                    ""id"": ""b7f5f45d-f4bf-45d2-ad3c-c32aefed932e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Face_South"",
                    ""type"": ""Button"",
                    ""id"": ""7e9268b6-1817-4cbf-8e2d-8258703287ec"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Face_East"",
                    ""type"": ""Button"",
                    ""id"": ""1d1a9b82-17c4-43ee-a0fe-e8cdaec88497"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Face_West"",
                    ""type"": ""Button"",
                    ""id"": ""0603a794-12f6-48ff-8b87-34af124e6ed0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Bumper_Left"",
                    ""type"": ""Button"",
                    ""id"": ""8bcf0ad0-0895-4d1d-aab6-8bf2e733b0a4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Bumper_Right"",
                    ""type"": ""Button"",
                    ""id"": ""7dad3366-567a-4ab5-8688-5ad4a688690f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Joystick_Left"",
                    ""type"": ""Button"",
                    ""id"": ""f43fae68-01dc-406e-948d-1ffd1a9473b5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Joystick_Right"",
                    ""type"": ""Button"",
                    ""id"": ""a9846b82-aa37-4c7a-be2e-fddf194f34f7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Start"",
                    ""type"": ""Button"",
                    ""id"": ""eeabcc59-cc36-4d27-9efc-4fab0960a61f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Button_Select"",
                    ""type"": ""Button"",
                    ""id"": ""78b10b2f-4854-4b46-bc7b-2bbe1d084a4e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dfe04e50-9de5-43bc-8781-3160c09452d3"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Joystick_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b0080a8-686c-4168-b365-9ec52af322b3"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Joystick_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fcd5b8e-5571-4634-a5dc-0038cbf424f2"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Joystick_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5497293-b854-4dda-981c-917fce610e33"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Joystick_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""942315e1-f8cf-46a4-907e-11e94d9da010"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Trigger_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""194e65e1-07b6-4f15-ae33-9f4d5d88bc89"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Trigger_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a763436a-e4eb-40c2-9935-9d2d4b7d4dd2"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Face_North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9380b5d1-eb5c-4b23-bfc1-4c6e45e8950b"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Dpad_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61c49376-77fc-49be-8e76-c924efb1f88b"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Dpad_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2acd65fc-71d4-457a-b773-4306352e6679"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Dpad_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1cf949c-f05e-4e9c-8724-62c1b790a754"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Dpad_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9e86328-4098-4f42-8069-400563019f19"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Face_South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4590171f-f6d2-4fe5-9098-0e8c2a7cae24"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Face_East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95028139-b0d2-47a3-bad0-e95ae76e2aaa"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Face_West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46e40ce0-29f3-4a49-88a0-a83669616366"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Bumper_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb297d98-fea2-411c-a841-045d2db00ec5"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Bumper_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b0b873f-acb7-4a34-b311-22df26b92530"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Joystick_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""479e5e9a-f4d6-492f-b4bd-55041de9ebed"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Joystick_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""626ea834-871c-49a6-9683-dbd125a801de"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d656c5d3-13f2-4a93-ae0c-f6c8981ad8d6"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Button_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Controls
        m_Controls = asset.FindActionMap("Controls", throwIfNotFound: true);
        m_Controls_Joystick_Left = m_Controls.FindAction("Joystick_Left", throwIfNotFound: true);
        m_Controls_Joystick_Right = m_Controls.FindAction("Joystick_Right", throwIfNotFound: true);
        m_Controls_Trigger_Left = m_Controls.FindAction("Trigger_Left", throwIfNotFound: true);
        m_Controls_Trigger_Right = m_Controls.FindAction("Trigger_Right", throwIfNotFound: true);
        m_Controls_Button_Dpad_Up = m_Controls.FindAction("Button_Dpad_Up", throwIfNotFound: true);
        m_Controls_Button_Dpad_Down = m_Controls.FindAction("Button_Dpad_Down", throwIfNotFound: true);
        m_Controls_Button_Dpad_Left = m_Controls.FindAction("Button_Dpad_Left", throwIfNotFound: true);
        m_Controls_Button_Dpad_Right = m_Controls.FindAction("Button_Dpad_Right", throwIfNotFound: true);
        m_Controls_Button_Face_North = m_Controls.FindAction("Button_Face_North", throwIfNotFound: true);
        m_Controls_Button_Face_South = m_Controls.FindAction("Button_Face_South", throwIfNotFound: true);
        m_Controls_Button_Face_East = m_Controls.FindAction("Button_Face_East", throwIfNotFound: true);
        m_Controls_Button_Face_West = m_Controls.FindAction("Button_Face_West", throwIfNotFound: true);
        m_Controls_Button_Bumper_Left = m_Controls.FindAction("Button_Bumper_Left", throwIfNotFound: true);
        m_Controls_Button_Bumper_Right = m_Controls.FindAction("Button_Bumper_Right", throwIfNotFound: true);
        m_Controls_Button_Joystick_Left = m_Controls.FindAction("Button_Joystick_Left", throwIfNotFound: true);
        m_Controls_Button_Joystick_Right = m_Controls.FindAction("Button_Joystick_Right", throwIfNotFound: true);
        m_Controls_Button_Start = m_Controls.FindAction("Button_Start", throwIfNotFound: true);
        m_Controls_Button_Select = m_Controls.FindAction("Button_Select", throwIfNotFound: true);
    }

    ~@GameControls()
    {
        UnityEngine.Debug.Assert(!m_Controls.enabled, "This will cause a leak and performance issues, GameControls.Controls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Controls
    private readonly InputActionMap m_Controls;
    private List<IControlsActions> m_ControlsActionsCallbackInterfaces = new List<IControlsActions>();
    private readonly InputAction m_Controls_Joystick_Left;
    private readonly InputAction m_Controls_Joystick_Right;
    private readonly InputAction m_Controls_Trigger_Left;
    private readonly InputAction m_Controls_Trigger_Right;
    private readonly InputAction m_Controls_Button_Dpad_Up;
    private readonly InputAction m_Controls_Button_Dpad_Down;
    private readonly InputAction m_Controls_Button_Dpad_Left;
    private readonly InputAction m_Controls_Button_Dpad_Right;
    private readonly InputAction m_Controls_Button_Face_North;
    private readonly InputAction m_Controls_Button_Face_South;
    private readonly InputAction m_Controls_Button_Face_East;
    private readonly InputAction m_Controls_Button_Face_West;
    private readonly InputAction m_Controls_Button_Bumper_Left;
    private readonly InputAction m_Controls_Button_Bumper_Right;
    private readonly InputAction m_Controls_Button_Joystick_Left;
    private readonly InputAction m_Controls_Button_Joystick_Right;
    private readonly InputAction m_Controls_Button_Start;
    private readonly InputAction m_Controls_Button_Select;
    public struct ControlsActions
    {
        private @GameControls m_Wrapper;
        public ControlsActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Joystick_Left => m_Wrapper.m_Controls_Joystick_Left;
        public InputAction @Joystick_Right => m_Wrapper.m_Controls_Joystick_Right;
        public InputAction @Trigger_Left => m_Wrapper.m_Controls_Trigger_Left;
        public InputAction @Trigger_Right => m_Wrapper.m_Controls_Trigger_Right;
        public InputAction @Button_Dpad_Up => m_Wrapper.m_Controls_Button_Dpad_Up;
        public InputAction @Button_Dpad_Down => m_Wrapper.m_Controls_Button_Dpad_Down;
        public InputAction @Button_Dpad_Left => m_Wrapper.m_Controls_Button_Dpad_Left;
        public InputAction @Button_Dpad_Right => m_Wrapper.m_Controls_Button_Dpad_Right;
        public InputAction @Button_Face_North => m_Wrapper.m_Controls_Button_Face_North;
        public InputAction @Button_Face_South => m_Wrapper.m_Controls_Button_Face_South;
        public InputAction @Button_Face_East => m_Wrapper.m_Controls_Button_Face_East;
        public InputAction @Button_Face_West => m_Wrapper.m_Controls_Button_Face_West;
        public InputAction @Button_Bumper_Left => m_Wrapper.m_Controls_Button_Bumper_Left;
        public InputAction @Button_Bumper_Right => m_Wrapper.m_Controls_Button_Bumper_Right;
        public InputAction @Button_Joystick_Left => m_Wrapper.m_Controls_Button_Joystick_Left;
        public InputAction @Button_Joystick_Right => m_Wrapper.m_Controls_Button_Joystick_Right;
        public InputAction @Button_Start => m_Wrapper.m_Controls_Button_Start;
        public InputAction @Button_Select => m_Wrapper.m_Controls_Button_Select;
        public InputActionMap Get() { return m_Wrapper.m_Controls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlsActions set) { return set.Get(); }
        public void AddCallbacks(IControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlsActionsCallbackInterfaces.Add(instance);
            @Joystick_Left.started += instance.OnJoystick_Left;
            @Joystick_Left.performed += instance.OnJoystick_Left;
            @Joystick_Left.canceled += instance.OnJoystick_Left;
            @Joystick_Right.started += instance.OnJoystick_Right;
            @Joystick_Right.performed += instance.OnJoystick_Right;
            @Joystick_Right.canceled += instance.OnJoystick_Right;
            @Trigger_Left.started += instance.OnTrigger_Left;
            @Trigger_Left.performed += instance.OnTrigger_Left;
            @Trigger_Left.canceled += instance.OnTrigger_Left;
            @Trigger_Right.started += instance.OnTrigger_Right;
            @Trigger_Right.performed += instance.OnTrigger_Right;
            @Trigger_Right.canceled += instance.OnTrigger_Right;
            @Button_Dpad_Up.started += instance.OnButton_Dpad_Up;
            @Button_Dpad_Up.performed += instance.OnButton_Dpad_Up;
            @Button_Dpad_Up.canceled += instance.OnButton_Dpad_Up;
            @Button_Dpad_Down.started += instance.OnButton_Dpad_Down;
            @Button_Dpad_Down.performed += instance.OnButton_Dpad_Down;
            @Button_Dpad_Down.canceled += instance.OnButton_Dpad_Down;
            @Button_Dpad_Left.started += instance.OnButton_Dpad_Left;
            @Button_Dpad_Left.performed += instance.OnButton_Dpad_Left;
            @Button_Dpad_Left.canceled += instance.OnButton_Dpad_Left;
            @Button_Dpad_Right.started += instance.OnButton_Dpad_Right;
            @Button_Dpad_Right.performed += instance.OnButton_Dpad_Right;
            @Button_Dpad_Right.canceled += instance.OnButton_Dpad_Right;
            @Button_Face_North.started += instance.OnButton_Face_North;
            @Button_Face_North.performed += instance.OnButton_Face_North;
            @Button_Face_North.canceled += instance.OnButton_Face_North;
            @Button_Face_South.started += instance.OnButton_Face_South;
            @Button_Face_South.performed += instance.OnButton_Face_South;
            @Button_Face_South.canceled += instance.OnButton_Face_South;
            @Button_Face_East.started += instance.OnButton_Face_East;
            @Button_Face_East.performed += instance.OnButton_Face_East;
            @Button_Face_East.canceled += instance.OnButton_Face_East;
            @Button_Face_West.started += instance.OnButton_Face_West;
            @Button_Face_West.performed += instance.OnButton_Face_West;
            @Button_Face_West.canceled += instance.OnButton_Face_West;
            @Button_Bumper_Left.started += instance.OnButton_Bumper_Left;
            @Button_Bumper_Left.performed += instance.OnButton_Bumper_Left;
            @Button_Bumper_Left.canceled += instance.OnButton_Bumper_Left;
            @Button_Bumper_Right.started += instance.OnButton_Bumper_Right;
            @Button_Bumper_Right.performed += instance.OnButton_Bumper_Right;
            @Button_Bumper_Right.canceled += instance.OnButton_Bumper_Right;
            @Button_Joystick_Left.started += instance.OnButton_Joystick_Left;
            @Button_Joystick_Left.performed += instance.OnButton_Joystick_Left;
            @Button_Joystick_Left.canceled += instance.OnButton_Joystick_Left;
            @Button_Joystick_Right.started += instance.OnButton_Joystick_Right;
            @Button_Joystick_Right.performed += instance.OnButton_Joystick_Right;
            @Button_Joystick_Right.canceled += instance.OnButton_Joystick_Right;
            @Button_Start.started += instance.OnButton_Start;
            @Button_Start.performed += instance.OnButton_Start;
            @Button_Start.canceled += instance.OnButton_Start;
            @Button_Select.started += instance.OnButton_Select;
            @Button_Select.performed += instance.OnButton_Select;
            @Button_Select.canceled += instance.OnButton_Select;
        }

        private void UnregisterCallbacks(IControlsActions instance)
        {
            @Joystick_Left.started -= instance.OnJoystick_Left;
            @Joystick_Left.performed -= instance.OnJoystick_Left;
            @Joystick_Left.canceled -= instance.OnJoystick_Left;
            @Joystick_Right.started -= instance.OnJoystick_Right;
            @Joystick_Right.performed -= instance.OnJoystick_Right;
            @Joystick_Right.canceled -= instance.OnJoystick_Right;
            @Trigger_Left.started -= instance.OnTrigger_Left;
            @Trigger_Left.performed -= instance.OnTrigger_Left;
            @Trigger_Left.canceled -= instance.OnTrigger_Left;
            @Trigger_Right.started -= instance.OnTrigger_Right;
            @Trigger_Right.performed -= instance.OnTrigger_Right;
            @Trigger_Right.canceled -= instance.OnTrigger_Right;
            @Button_Dpad_Up.started -= instance.OnButton_Dpad_Up;
            @Button_Dpad_Up.performed -= instance.OnButton_Dpad_Up;
            @Button_Dpad_Up.canceled -= instance.OnButton_Dpad_Up;
            @Button_Dpad_Down.started -= instance.OnButton_Dpad_Down;
            @Button_Dpad_Down.performed -= instance.OnButton_Dpad_Down;
            @Button_Dpad_Down.canceled -= instance.OnButton_Dpad_Down;
            @Button_Dpad_Left.started -= instance.OnButton_Dpad_Left;
            @Button_Dpad_Left.performed -= instance.OnButton_Dpad_Left;
            @Button_Dpad_Left.canceled -= instance.OnButton_Dpad_Left;
            @Button_Dpad_Right.started -= instance.OnButton_Dpad_Right;
            @Button_Dpad_Right.performed -= instance.OnButton_Dpad_Right;
            @Button_Dpad_Right.canceled -= instance.OnButton_Dpad_Right;
            @Button_Face_North.started -= instance.OnButton_Face_North;
            @Button_Face_North.performed -= instance.OnButton_Face_North;
            @Button_Face_North.canceled -= instance.OnButton_Face_North;
            @Button_Face_South.started -= instance.OnButton_Face_South;
            @Button_Face_South.performed -= instance.OnButton_Face_South;
            @Button_Face_South.canceled -= instance.OnButton_Face_South;
            @Button_Face_East.started -= instance.OnButton_Face_East;
            @Button_Face_East.performed -= instance.OnButton_Face_East;
            @Button_Face_East.canceled -= instance.OnButton_Face_East;
            @Button_Face_West.started -= instance.OnButton_Face_West;
            @Button_Face_West.performed -= instance.OnButton_Face_West;
            @Button_Face_West.canceled -= instance.OnButton_Face_West;
            @Button_Bumper_Left.started -= instance.OnButton_Bumper_Left;
            @Button_Bumper_Left.performed -= instance.OnButton_Bumper_Left;
            @Button_Bumper_Left.canceled -= instance.OnButton_Bumper_Left;
            @Button_Bumper_Right.started -= instance.OnButton_Bumper_Right;
            @Button_Bumper_Right.performed -= instance.OnButton_Bumper_Right;
            @Button_Bumper_Right.canceled -= instance.OnButton_Bumper_Right;
            @Button_Joystick_Left.started -= instance.OnButton_Joystick_Left;
            @Button_Joystick_Left.performed -= instance.OnButton_Joystick_Left;
            @Button_Joystick_Left.canceled -= instance.OnButton_Joystick_Left;
            @Button_Joystick_Right.started -= instance.OnButton_Joystick_Right;
            @Button_Joystick_Right.performed -= instance.OnButton_Joystick_Right;
            @Button_Joystick_Right.canceled -= instance.OnButton_Joystick_Right;
            @Button_Start.started -= instance.OnButton_Start;
            @Button_Start.performed -= instance.OnButton_Start;
            @Button_Start.canceled -= instance.OnButton_Start;
            @Button_Select.started -= instance.OnButton_Select;
            @Button_Select.performed -= instance.OnButton_Select;
            @Button_Select.canceled -= instance.OnButton_Select;
        }

        public void RemoveCallbacks(IControlsActions instance)
        {
            if (m_Wrapper.m_ControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlsActions @Controls => new ControlsActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IControlsActions
    {
        void OnJoystick_Left(InputAction.CallbackContext context);
        void OnJoystick_Right(InputAction.CallbackContext context);
        void OnTrigger_Left(InputAction.CallbackContext context);
        void OnTrigger_Right(InputAction.CallbackContext context);
        void OnButton_Dpad_Up(InputAction.CallbackContext context);
        void OnButton_Dpad_Down(InputAction.CallbackContext context);
        void OnButton_Dpad_Left(InputAction.CallbackContext context);
        void OnButton_Dpad_Right(InputAction.CallbackContext context);
        void OnButton_Face_North(InputAction.CallbackContext context);
        void OnButton_Face_South(InputAction.CallbackContext context);
        void OnButton_Face_East(InputAction.CallbackContext context);
        void OnButton_Face_West(InputAction.CallbackContext context);
        void OnButton_Bumper_Left(InputAction.CallbackContext context);
        void OnButton_Bumper_Right(InputAction.CallbackContext context);
        void OnButton_Joystick_Left(InputAction.CallbackContext context);
        void OnButton_Joystick_Right(InputAction.CallbackContext context);
        void OnButton_Start(InputAction.CallbackContext context);
        void OnButton_Select(InputAction.CallbackContext context);
    }
}
