// Generated by ChatGPT and Riko Balakit/Pearl Grey
using UnityEngine;
using UnityEngine.InputSystem;

public class TestInputActions : MonoBehaviour
{
    private GameControls _gameControls;

    private void Awake()
    {
        _gameControls = new GameControls();

        // Joysticks
        _gameControls.Controls.Joystick_Left.performed += ctx => Debug.Log($"Left Stick: {ctx.ReadValue<Vector2>()}");
        _gameControls.Controls.Joystick_Right.performed += ctx => Debug.Log($"Right Stick: {ctx.ReadValue<Vector2>()}");

        // Triggers
        _gameControls.Controls.Trigger_Left.performed += ctx => Debug.Log($"Left Trigger: {ctx.ReadValue<float>()}");
        _gameControls.Controls.Trigger_Right.performed += ctx => Debug.Log($"Right Trigger: {ctx.ReadValue<float>()}");

        // D-Pad
        _gameControls.Controls.Button_Dpad_Up.performed += _ => Debug.Log("D-Pad Up Pressed");
        _gameControls.Controls.Button_Dpad_Down.performed += _ => Debug.Log("D-Pad Down Pressed");
        _gameControls.Controls.Button_Dpad_Left.performed += _ => Debug.Log("D-Pad Left Pressed");
        _gameControls.Controls.Button_Dpad_Right.performed += _ => Debug.Log("D-Pad Right Pressed");

        // Face Buttons
        _gameControls.Controls.Button_Face_North.performed += _ => Debug.Log("Button North Pressed");
        _gameControls.Controls.Button_Face_South.performed += _ => Debug.Log("Button South Pressed");
        _gameControls.Controls.Button_Face_East.performed += _ => Debug.Log("Button East Pressed");
        _gameControls.Controls.Button_Face_West.performed += _ => Debug.Log("Button West Pressed");

        // Bumpers
        _gameControls.Controls.Button_Bumper_Left.performed += _ => Debug.Log("Left Bumper Pressed");
        _gameControls.Controls.Button_Bumper_Right.performed += _ => Debug.Log("Right Bumper Pressed");

        // Joystick Buttons
        _gameControls.Controls.Button_Joystick_Left.performed += _ => Debug.Log("Left Stick Pressed");
        _gameControls.Controls.Button_Joystick_Right.performed += _ => Debug.Log("Right Stick Pressed");

        // Start and Select
        _gameControls.Controls.Button_Start.performed += _ => Debug.Log("Start Button Pressed");
        _gameControls.Controls.Button_Select.performed += _ => Debug.Log("Select Button Pressed");
    }

    private void OnEnable()
    {
        _gameControls.Controls.Enable();
    }

    private void OnDisable()
    {
        _gameControls.Controls.Disable();
    }
}
